CONSTANTS = {
    'DAILY_TICKETS': 1,
    'INVOCATION_COST': 1,
    'RARITY_PRICE': {
        'X': 100,
        'SS': 50,
        'S': 25,
        'A': 10,
        'B': 5,
        'C': 1,
        'D': 0.5,
        'E': 0.25,
        'F': 0.1,
    },
    'RARITY_CHANCE': {
        'X': 0.01,
        'SS': 0.02,
        'S': 0.05,
        'A': 0.1,
        'B': 0.15,
        'C': 0.2,
        'D': 0.15,
        'E': 0.1,
        'F': 0.1,
    },
}