{'X Drake': 'https://i.imgur.com/PjvOkQl.png',
 'Usopp': '',
 'Urouge': 'https://i.imgur.com/bxeWykZ.png',
 'Smoothie': 'https://i.imgur.com/Dzbl4ig.gif',
 'Shirahoshi': 'https://i.imgur.com/P0iyWbd.png',
 'Shakuyaku': 'https://i.imgur.com/zrxGOl1.png',
 'Sabo': 'https://i.imgur.com/vjcu8Gg.gif',
 'Rob Lucci': 'https://i.imgur.com/aewCvhP.gif',
 'Pell': 'https://i.imgur.com/fzBiN7h.png',
 'Nico Robin': 'https://i.imgur.com/tiC5mlA.gif',
 'Nico Olvia': 'https://i.imgur.com/8qkBqnx.png',
 'Marco': 'https://i.imgur.com/LOo1j5P.gif',
 'Magellan': 'https://i.imgur.com/nvHpUU8.png',
 'Doflamingo': 'https://i.imgur.com/HHCqR9J.jpg',
 'Kozuki Hiyori': 'https://i.imgur.com/8X1yZq5.png',
 'Koby': 'https://i.imgur.com/OtsQuBI.png',
 'Koby (Jeune)': 'https://i.imgur.com/JCiQVPw.png',
 'Kinemon': 'https://i.imgur.com/0nvh6Kd.jpg',
 'Katakuri': 'https://i.imgur.com/5z0sR8N.gif',
 'Kalifa': 'https://i.imgur.com/qL6KDas.png',
 'Kaku': 'https://i.imgur.com/CK98WHJ.gif',
 'Jewelry Bonney': 'https://i.imgur.com/SY0dOWb.png',
 'Jabura': 'https://i.imgur.com/Ao620Jo.png',
 'Inazuma': 'https://i.imgur.com/PyUiXXv.png',
 'Hyogoro': 'https://i.imgur.com/4jGoLEH.png',
 'Hody Jones': 'https://i.imgur.com/toloIlI.png',
 'Hina': 'https://i.imgur.com/2tbPDP4.png',
 'Variété': 'https://i.imgur.com/h2NDgz5.png',
 'Gol D. Roger': 'https://i.imgur.com/jhHkjfz.gif',
 'Gecko Moria': 'https://i.imgur.com/eFgXOcJ.png',
 'Kozuki Oden': 'https://i.imgur.com/mACnc1L.jpg',
 'Franky': 'https://i.imgur.com/U08oSKn.gif',
 'Dracule Mihawk': 'https://i.imgur.com/UICGMYV.gif',
 'Corazon': 'https://i.imgur.com/iKB20nv.gif',
 'Capone Bege': 'https://i.imgur.com/wJTOHqS.png',
 'Caesar Clown': 'https://i.imgur.com/r3VfFez.gif',
 'Ener': 'https://i.imgur.com/s9LuY59.png',
 'Boa Hancock': 'https://i.imgur.com/ZWtbLYH.gif',
 'Blueno': 'https://i.imgur.com/DzsdApN.png',
 'Black Maria': 'https://i.imgur.com/4v43VxP.jpg',
 'Bepo': 'https://i.imgur.com/osDpI6s.gif',
 'Basil Hawkins': 'https://i.imgur.com/amftYKa.png',
 'Arlong': 'https://i.imgur.com/MXsMw7m.jpg',
 'Alvida': 'https://i.imgur.com/HRdKD0e.jpg',
 'Otsutsuki Hagomoro': 'https://i.imgur.com/bn7KwyD.gif',
 'Momoshiki Otsutsuki': 'https://cdn.discordapp.com/attachments/805054171661336590/817046334371921941/Momoshiki.gif',
 'Otsutsuki Indra': 'https://i.imgur.com/dlXLwgN.gif',
 'Otsutsuki Ashura': 'https://i.imgur.com/aRMeDPa.gif',
 'Gaï Maito (Huit Portes)': 'https://i.imgur.com/UlM0N3p.gif',
 'Third Tsuchikage': 'https://cdn.discordapp.com/attachments/805054171661336590/817395389970776094/ONOIKI.gif',
 'Temari (Adulte)': 'https://cdn.discordapp.com/attachments/805054171661336590/817119251750977566/TEMARI.gif',
 'Temari': 'https://i.imgur.com/cG3keuO.gif',
 'Temari (Jeune)': 'https://i.imgur.com/XjU3vXb.jpg',
 'Suigetsu Hozuki': 'https://i.imgur.com/E6d3rSt.gif',
 'Shisui (Susanoo)': 'https://i.imgur.com/rC1YYxN.png',
 'Shisui Uchiha': 'https://i.imgur.com/67NNZm3.gif',
 'Shino Aburame': 'https://i.imgur.com/mVxNOAM.png',
 'Shikamaru Nara': 'https://i.imgur.com/KySPqGV.gif',
 'Sasori': 'https://i.imgur.com/RlpI6Rd.gif',
 'Sai': 'https://i.imgur.com/03ICbLj.gif',
 'Neji Hyūga': 'https://i.imgur.com/acFMgGN.gif',
 'Pain': 'https://i.imgur.com/1bv6EmW.gif',
 'Nagato': 'https://i.imgur.com/vjH3pqt.png',
 'Kurama': 'https://i.imgur.com/rHu7vIe.gif',
 'Mei Terumī': 'https://i.imgur.com/JTaGhQQ.gif',
 'Mangetsu Hozuki': 'https://i.imgur.com/Oy3puRA.png',
 'Kurenai Yūhi (Adulte)': 'https://i.imgur.com/KT4DQ9Q.gif',
 'Kurenai Yūhi': 'https://i.imgur.com/1E2Ux2a.png',
 'Kisame Hoshigaki': 'https://i.imgur.com/50KuDl3.gif',
 'Kaguya': 'https://i.imgur.com/u7viV9C.gif',
 'Kabuto Yakushi': 'https://i.imgur.com/hKkOwaY.gif',
 'Iruka Umino': 'https://i.imgur.com/p0YmijL.png',
 'Boruto (Adulte)': 'https://cdn.discordapp.com/attachments/805054171661336590/817503818375102484/BORUTO_GIF.gif',
 'Boruto': 'https://i.imgur.com/WKzYzHi.png',
 'Hinata Hyūga (Adulte)': 'https://i.imgur.com/VsFYMA1.gif',
 'Hinata Hyūga': 'https://cdn.discordapp.com/attachments/805054171661336590/817123552176242709/hinata.gif',
 'Hinata Hyūga (Jeune)': 'https://i.imgur.com/x4IZQHb.png',
 'Hidan': 'https://i.imgur.com/Nz7dGAU.png',
 'Hanzo': 'https://i.imgur.com/vw1NVva.gif',
 'Haku et Zabuza': 'https://i.imgur.com/fT4IFYl.gif',
 'Haku (Edo Tensei)': 'https://i.imgur.com/xOobUgV.gif',
 'Haku': 'https://i.imgur.com/vqQD56N.png',
 'Bucciarati': 'https://i.imgur.com/2js7rsD.png',
 'Ebisu': 'https://i.imgur.com/qWpczNK.png',
 'Deidara': 'https://i.imgur.com/k83MFjs.gif',
 'Darui': 'https://i.imgur.com/4agHAoM.gif',
 'Danzo Shimura': 'https://i.imgur.com/jn2y84k.gif',
 'Asuma Sarutobi': 'https://i.imgur.com/lGIqLP3.gif',
 'Fourth Raikage': 'https://i.imgur.com/cYeh5dS.gif',
 'Necrozma': 'https://i.imgur.com/ZFDtlK4.png',
 'Lunala': 'https://i.imgur.com/Uq2SY2u.png',
 'Solgaleo': 'https://i.imgur.com/4zkBJqA.gif',
 'Volcanion': 'https://i.imgur.com/pm8xhIh.gif',
 'Yveltal': 'https://i.imgur.com/c6UT3ho.gif',
 'Xerneas': 'https://i.imgur.com/8QQKYrB.gif',
 'Nymphali': 'https://i.imgur.com/GbGIdXT.gif',
 'Némélios': 'https://i.imgur.com/GdSluJm.gif',
 'Hélionceau': 'https://i.imgur.com/Xm6NpS4.png',
 'Amphinobi': 'https://i.imgur.com/rjihI5s.png',
 'Croâporal': 'https://i.imgur.com/gC5PF17.png',
 'Grenousse': 'https://i.imgur.com/vnwWN3s.png',
 'Goupelin': 'https://i.imgur.com/BtOfPok.gif',
 'Roussil': 'https://i.imgur.com/2xgh5n0.png',
 'Feunnec': 'https://i.imgur.com/N2iWUrC.png',
 'Kyurem': 'https://cdn.discordapp.com/attachments/805054171661336590/816641070334869514/2.gif',
 'Zekrom': 'https://i.imgur.com/yzxPPmo.gif',
 'Reshiram': 'https://i.imgur.com/mYRDWbj.gif',
 'Tranchodon': 'https://i.imgur.com/PPqlpYD.gif',
 'Incisache': 'https://i.imgur.com/PhjW0mr.png',
 'Coupenotte': 'https://i.imgur.com/B8yghrS.png',
 'Zorua': 'https://i.imgur.com/FqZ1NPp.png',
 'Clamiral': 'https://i.imgur.com/WcR26An.gif',
 'Mateloutre': 'https://i.imgur.com/cAzCa7Q.png',
 'Moustillon': 'https://i.imgur.com/mwK8a87.png',
 'Roitiflam': 'https://i.imgur.com/gJppBUG.gif',
 'Grotichon': 'https://i.imgur.com/QBqLpp0.png',
 'Gruikui': 'https://i.imgur.com/XUoYaai.png',
 'Arceus': 'https://cdn.discordapp.com/attachments/805054171661336590/816429859450257470/ARCEUS.gif',
 'Darkrai': 'https://i.imgur.com/6VOmMEa.gif',
 'Giratina': 'https://i.imgur.com/BpfLcBJ.gif',
 'Dialga et Palkia': 'https://i.imgur.com/0LAOriz.gif',
 'Givrali': 'https://i.imgur.com/1UQKMX6.gif',
 'Phyllali': 'https://i.imgur.com/CXUE4ZP.gif',
 'Maganon': 'https://i.imgur.com/bNykYxA.gif',
 'Élekable': 'https://i.imgur.com/WcoeNNw.gif',
 'Riolu': 'https://i.imgur.com/RZoQ7kQ.jpg',
 'Goinfrex': 'https://i.imgur.com/XHeG3Ic.gif',
 'Mega Carchacrok': 'https://i.imgur.com/NMBQAD5.gif',
 'Carchacrok': 'https://i.imgur.com/KkjCDYh.gif',
 'Carmache': 'https://i.imgur.com/UuSUqNo.gif',
 'Griknot': 'https://i.imgur.com/IDuQg9n.png',
 'Luxray': 'https://i.imgur.com/gbPyGG7.gif',
 'Lixy': 'https://i.imgur.com/Fz29170.gif',
 'Keunotor': 'https://i.imgur.com/o4938sk.png',
 'Pingoléon': 'https://i.imgur.com/ntRPBiI.gif',
 'Prinplouf': 'https://i.imgur.com/RiW7oSl.png',
 'Tiplouf': 'https://i.imgur.com/hpjmH8A.png',
 'Simiabraz': 'https://i.imgur.com/3soewnn.gif',
 'Chimpenfeu': 'https://i.imgur.com/xJHwlxd.png',
 'Ouisticram': 'https://i.imgur.com/yXOI6oR.jpg',
 'Torterra': 'https://i.imgur.com/6ctjlB7.gif',
 'Boskara': 'https://i.imgur.com/wokqroy.png',
 'Tortipouss': 'https://i.imgur.com/LWtw1mg.png',
 'Mega Rayquaza': 'https://i.imgur.com/2tUnUWb.png',
 'Deoxys': 'https://i.imgur.com/rQvHM8l.gif',
 'Eternatus': 'https://i.imgur.com/XUoYaai.png',
 'Rayquaza': 'https://i.imgur.com/vpd4qHY.gif',
 'Primo Groudon': 'https://i.imgur.com/dBBnfAA.gif',
 'Groudon': 'https://cdn.discordapp.com/attachments/805054171661336590/816331077094211595/groudon.gif',
 'Primo Kyogre': 'https://i.imgur.com/HiPD4yG.gif',
 'Kyogre': 'https://i.imgur.com/9FiUz6N.gif',
 'Latias et Latios': 'https://i.imgur.com/XlzSuOD.gif',
 'Drattak': 'https://i.imgur.com/a8wjDIZ.gif',
 'Drackhaus': 'https://i.imgur.com/cm3u9CT.png',
 'Draby': 'https://i.imgur.com/cMNGrf8.jpg',
 'Laggron': 'https://i.imgur.com/TVRHV9e.gif',
 'Flobio': 'https://i.imgur.com/Fpaj7xh.jpg',
 'Gobou': 'https://i.imgur.com/Xd9quZm.jpg',
 'Mega Braségali': 'https://i.imgur.com/Lus5a0P.gif',
 'Braségali': 'https://i.imgur.com/JceLEMB.gif',
 'Poussifeu': 'https://i.imgur.com/82aDpn0.jpg',
 'Jungko': 'https://i.imgur.com/Vh9Y4Lw.gif',
 'Massko': 'https://i.imgur.com/Ig5GHtd.gif',
 'Arcko': 'https://i.imgur.com/4ggPUCf.jpg',
 'Celebi': 'https://i.imgur.com/aMiXUpF.gif',
 'Tyranocif': 'https://cdn.discordapp.com/attachments/805054171661336590/816298274264055811/Tyrannocif.gif',
 'Embrylex': 'https://i.imgur.com/4VitIDh.png',
 'Suicune': 'https://i.imgur.com/Zuj7ey4.gif',
 'Entei': 'https://i.imgur.com/mr6U0kj.gif',
 'Raikou': 'https://i.imgur.com/adaPfNr.gif',
 'Magby': 'https://i.imgur.com/qBB4xrL.gif',
 'Élekid': 'https://i.imgur.com/XZpefrS.png',
 'Noctali': 'https://i.imgur.com/60aTpkX.gif',
 'Mentali': 'https://i.imgur.com/3TLvnr4.gif',
 'Pichu': 'https://i.imgur.com/FcEORIu.jpg',
 'Aligatueur': 'https://i.imgur.com/txWsKfJ.gif',
 'Crocrodil': 'https://i.imgur.com/Eauvnpc.png',
 'Kaiminus': 'https://i.imgur.com/bkQvIm0.png',
 'Typhlosion': 'https://cdn.discordapp.com/attachments/805054171661336590/816047331283435550/TYPHLO.gif',
 'Feurisson': 'https://i.imgur.com/kOQNkKv.jpg',
 'Héricendre': 'https://i.imgur.com/PnV5242.gif',
 'Méganium': 'https://i.imgur.com/j2exfYg.png',
 'Macronium': 'https://i.imgur.com/YWFYkLi.jpg',
 'Germignon': 'https://i.imgur.com/GH5sYGm.jpg',
 'Minidraco': 'https://i.imgur.com/7VLtXfz.gif',
 'Draco': 'https://i.imgur.com/NwbjuTX.gif',
 'Dracolosse': 'https://i.imgur.com/TAxElqg.gif',
 'Sulfura': 'https://i.imgur.com/uqPKoZx.gif',
 'Électhor': 'https://i.imgur.com/lSH2evW.gif',
 'Artikodin': 'https://i.imgur.com/o3UEVxJ.gif',
 'Ronflex': 'https://i.imgur.com/xKGGIua.gif',
 'Pyroli': 'https://i.imgur.com/16vWY2O.jpg',
 'Voltali': 'https://i.imgur.com/IrtE4JZ.gif',
 'Aquali': 'https://i.imgur.com/D05zSha.jpg',
 'Évoli': 'https://i.imgur.com/3PZX2tq.gif',
 'Métamorph': 'https://i.imgur.com/VDENAHK.gif',
 'Lokhlass': 'https://i.imgur.com/ugqMEkN.gif',
 'Léviator Rouge': 'https://i.imgur.com/cm2Wiwp.gif',
 'Léviator': 'https://i.imgur.com/heINN3d.jpg',
 'Magicarpe': 'https://i.imgur.com/lnaXA9X.png',
 'Magmar': 'https://i.imgur.com/8c2jCR0.gif',
 'Ectoplasma': 'https://i.imgur.com/PITlLpZ.gif',
 'Spectrum': 'https://i.imgur.com/5cY9fgt.png',
 'Fantominus': 'https://i.imgur.com/aDc84xj.png',
 'Ramoloss': 'https://i.imgur.com/Y0FmxyW.jpg',
 'Mackogneur': 'https://i.imgur.com/Tuusmfd.gif',
 'Machoc': 'https://i.imgur.com/gd96c4u.gif',
 'Alakazam': 'https://i.imgur.com/FMN06YJ.gif',
 'Kadabra': 'https://i.imgur.com/3yMRbpj.jpg',
 'Abra': 'https://i.imgur.com/lfwKpXO.png',
 'Arcanin': 'https://i.imgur.com/2uajDEa.gif',
 'Caninos': 'https://i.imgur.com/TwMykm7.png',
 'Colossinge': 'https://i.imgur.com/I3AowOz.gif',
 'Férosinge': 'https://i.imgur.com/GAmR9bM.png',
 'Psykokwak': 'https://i.imgur.com/kRX9wPF.gif',
 'Miaouss': 'https://i.imgur.com/RhhcF2A.png',
 'Feunard': 'https://i.imgur.com/oHlH3w8.gif',
 'Goupix': 'https://i.imgur.com/sJpWyE1.png',
 'Raichu': 'https://i.imgur.com/54X4ACm.png',
 'Pikachu': 'https://i.imgur.com/y4f3d7u.png',
 'Rattatac': 'https://i.imgur.com/zWoCZEA.png',
 'Rattata': 'https://i.imgur.com/oLFnKu8.jpg',
 'Roucarnage': 'https://i.imgur.com/84qp0SZ.gif',
 'Roucoups': 'https://i.imgur.com/geIIjNS.gif',
 'Roucool': 'https://i.imgur.com/lEy9Oi5.jpg',
 'Tortank': 'https://i.imgur.com/uTmGGV2.gif',
 'Carabaffe': 'https://i.imgur.com/MDsPayf.png',
 'Carapuce': 'https://i.imgur.com/dewnkqQ.jpg',
 'Dracaufeu': 'https://i.imgur.com/jVKevKZ.gif',
 'Reptincel': 'https://i.imgur.com/D2IjXcY.png',
 'Salamèche': 'https://i.imgur.com/d8VI32c.jpg',
 'Florizarre': 'https://i.imgur.com/7jcqfH8.gif',
 'Herbizarre': 'https://i.imgur.com/2vhJ9xY.gif',
 'Bulbizarre': 'https://i.imgur.com/mrAPS6D.png',
 'Akamaru': 'https://i.imgur.com/BE0UhSD.png',
 'Oingo et Boingo': 'https://i.imgur.com/zH75hhI.jpg',
 'Kon': 'https://i.imgur.com/7LD5zWk.png',
 'Gaimon': 'https://i.imgur.com/vV2JD2E.png',
 'Sakura (Jeune)': 'https://i.imgur.com/LCZRIJZ.jpg',
 'Sasuke (Jeune)': 'https://i.imgur.com/buawRqo.png',
 'Naruto (Jeune)': 'https://i.imgur.com/4bCp2Bv.png',
 'Konohamaru': 'https://i.imgur.com/aZoURBF.png',
 'Saibaman': 'https://static.wikia.nocookie.net/dragonball/images/a/a1/SaiabamenInfoBox.png/revision/latest/top-crop/width/360/height/450?cb=20180410165552',
 'Imran': 'https://www.supersoluce.com/sites/default/files/node/60138/gobe.png',
 'Shoto (Enfant)': 'https://i.imgur.com/pztPpVx.jpg',
 'Izuku (Enfant)': 'https://i.imgur.com/yKwpyPm.png',
 'Chopper': 'https://i.imgur.com/eSoVui2.png',
 'Krillin': 'https://i.imgur.com/UBZx0cv.png',
 'Mikasa (Jeune)': 'https://i.imgur.com/4P3Amuh.jpg',
 'Armin (Jeune)': 'https://i.imgur.com/TdOBgTO.png',
 'Tenten (Jeune)': 'https://i.imgur.com/UcZPvOv.png',
 'Kiba (Jeune)': 'https://i.imgur.com/Dtsv3hg.png',
 'Rock Lee': 'https://i.imgur.com/1V4WwG9.png',
 'Trunks (Jeune)': 'https://i.imgur.com/p05GJns.jpg',
 'Baggy': 'https://i.imgur.com/9aeBJHQ.jpg',
 'Gaimon et ses amis': 'https://i.imgur.com/JRxXdvt.png',
 'Jiren': 'https://i.imgur.com/XZawkno.gif',
 'Bulma': 'https://i.imgur.com/covoW98.png',
 'Bulma (Jeune)': 'https://i.imgur.com/nmyRKzl.png',
 'Yamcha': 'https://i.imgur.com/7gdmL5a.jpg',
 'Daron Hakim': 'https://i.imgur.com/6VkH5Qg.png',
 'Son Goku (Petit)': 'https://i.imgur.com/HvlwNlC.jpg',
 'Ussop': 'https://i.imgur.com/oJD4qsv.gif',
 'Son Goten': 'https://i.imgur.com/Hv74r0d.png',
 'Rin': 'https://i.imgur.com/1hhrS6i.png',
 'Ishida': 'https://i.imgur.com/q4C40vK.jpg',
 'Uryu Ishida': 'https://i.imgur.com/qwPKhrk.gif',
 'Ryuken Ishida': 'https://i.imgur.com/nOA4UJj.png',
 'Ukitake': '',
 'Mayuri Kurotsuchi': 'https://i.imgur.com/ZbjINfP.png',
 'Kaname Tosen': 'https://i.imgur.com/2jFDwuJ.png',
 'Komamura': 'https://i.imgur.com/7HyUEt3.png',
 'Shunsui Kyoraku': 'https://i.imgur.com/7DGfP2z.gif',
 'Unohana': 'https://i.imgur.com/5Od8a0Q.png',
 'Yamamoto': 'https://i.imgur.com/EGYHcBd.gif',
 'Coyote Stark': 'https://i.imgur.com/nXUhgKD.png',
 'Shinji Hirako': 'https://i.imgur.com/nXUhgKD.png',
 'Grimmjow': 'https://i.imgur.com/RKJxwy8.gif',
 'Grimmjow (Pantera)': 'https://i.imgur.com/DrQ2zV7.gif',
 'Ulquiorra': 'https://i.imgur.com/OaYNXCg.gif',
 'Ulquiorra (Murciélago)': 'https://i.imgur.com/cXrit5G.gif',
 'Renji Abarai': 'https://i.imgur.com/NBGO28d.gif',
 'Rangiku': 'https://i.imgur.com/CxCxRqv.gif',
 'Toshiro Hitsugaya': 'https://i.imgur.com/R9S0Qa4.gif',
 'Gin Ichimaru': 'https://i.imgur.com/kveTtpS.gif',
 'Kenpachi Zaraki': 'https://i.imgur.com/vWwyc9V.gif',
 'Sosuke Aizen (Capitaine)': 'https://i.imgur.com/nnWVdai.gif',
 'Sosuke Aizen': 'https://i.imgur.com/SraH2OW.gif',
 'Byakuya Kuchiki': 'https://i.imgur.com/35R4Uw4.gif',
 'Rukia Kuchiki': 'https://i.imgur.com/6FGRxti.jpg',
 'Vegeta': 'https://i.imgur.com/Lg5hZBC.png',
 'Son Goku': 'https://i.imgur.com/bEqQbPL.png',
 'Sanji (Cuisinier)': 'https://i.imgur.com/hkob0Vu.jpg',
 'Luffy': 'https://i.imgur.com/Q4WkysZ.png',
 'Luffy (Enfant)': 'https://i.imgur.com/xb0DwT3.gif',
 'Sasuke': 'https://i.imgur.com/U6RTC5j.png',
 'Sakura': 'https://i.imgur.com/lzTTP90.png',
 'Itadori': 'https://i.imgur.com/KxwCmFA.png',
 'Naruto': 'https://i.imgur.com/I8iqi73.png',
 'Eren (Jeune)': 'https://i.imgur.com/iURmWW2.png',
 'Mehmed': 'https://www.sortiraparis.com/images/58/54953/259273-baby-boss-le-nouveau-film-d-animation-de-dreamworks.jpg',
 'Ichigo': 'https://i.imgur.com/IBeNsEb.gif',
 'Gaara (Jeune)': 'https://i.imgur.com/cmk107r.png',
 'Minato (Jeune)': 'https://i.imgur.com/hssaI1B.jpg',
 'Son Gohan': 'https://i.imgur.com/W3zZF7c.png',
 'Obito (Jeune)': 'https://i.imgur.com/znn63Rs.jpg',
 'Orihime (Humaine)': 'https://i.imgur.com/KFgsKDV.png',
 'Armin': 'https://i.imgur.com/ExxI5r5.png',
 'Megumi': 'https://i.imgur.com/l46onBN.jpg',
 'Inumaki': 'https://i.imgur.com/6wyesDT.png',
 'Nobara': 'https://i.imgur.com/Q8Jgmu4.jpg',
 'Sniper King': 'https://cdn.discordapp.com/attachments/804401351080542269/809008932218470441/sniperking.gif',
 'Orihime': 'https://i.imgur.com/hgvXcf5.png',
 'Kakashi (Jeune)': 'https://i.imgur.com/h0zItad.gif',
 'Mikasa': 'https://i.imgur.com/hVS545Y.png',
 'Tenten': 'https://i.imgur.com/s6MEz46.png',
 'Kiba': 'https://cdn.discordapp.com/attachments/804401351080542269/808361778567970876/KIBA.gif',
 'Rock Lee (Cinq Portes)': 'https://cdn.discordapp.com/attachments/804401351080542269/808358879066587136/1524701909_rock_lee_open_the_door.gif',
 'Trunks Ssj': 'https://cdn.discordapp.com/attachments/804401351080542269/809018475423072256/main-qimg-027945a5a3d7603b66b4b3a9edc8a432.gif',
 'Son Goten Ssj': 'https://i.imgur.com/zwU8bhi.gif',
 'Piccolo': 'https://i.imgur.com/GpJrdaL.gif',
 'Goten et Trunks Ssj': 'https://i.imgur.com/yUuFMRB.gif',
 'Baggy (Corsaire)': 'https://i.imgur.com/IXOozeh.jpg',
 'Super Vegeta': 'https://i.imgur.com/DmsmDGC.png',
 'Son Goku Ssj': 'https://i.imgur.com/EJjpdIC.gif',
 'Eren': 'https://i.imgur.com/zTlTovV.gif',
 'Luffy (Gear 2)': 'https://i.imgur.com/zwJ7RJW.gif',
 'Sasuke (Susanoo)': 'https://cdn.discordapp.com/attachments/803713643198808115/803744740532027452/unknown.png',
 'Naruto (Sage Mode)': 'https://i.imgur.com/yHx0iBt.jpg',
 'Shrek Gragas': 'https://pbs.twimg.com/media/EPPp0dBW4AEH_P1.jpg',
 'Gabin': 'https://cdn.discordapp.com/attachments/474920758334717969/803347033712099328/unknown.png',
 'Ichigo (Bankai)': 'https://i.imgur.com/ddG92vl.gif',
 'Minato (Jonin)': 'https://i.imgur.com/T9dt8Bw.jpg',
 'Izuna': 'https://i.imgur.com/OxGlzHg.png',
 'Obito (Sharingan)': 'https://i.imgur.com/VjkkH1U.jpg',
 'All Might (Sans Alter)': 'https://i.imgur.com/EuDnBWi.jpg',
 'Zyra': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zyra_0.jpg',
 'Zoe': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zoe_0.jpg',
 'Zilean': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zilean_0.jpg',
 'Ziggs': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ziggs_0.jpg',
 'Zed': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zed_0.jpg',
 'Zac': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Zac_0.jpg',
 'Yuumi': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yuumi_0.jpg',
 'Yorick': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yorick_0.jpg',
 'Yone': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yone_0.jpg',
 'Yasuo': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Yasuo_0.jpg',
 'Xin Zhao': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/XinZhao_0.jpg',
 'Xerath': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xerath_0.jpg',
 'Xayah': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Xayah_0.jpg',
 'Warwick': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Warwick_0.jpg',
 'Volibear': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Volibear_0.jpg',
 'Vladimir': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vladimir_0.jpg',
 'Viktor': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Viktor_0.jpg',
 'Viego': 'https://cdn.discordapp.com/attachments/805054171661336590/819257929021653009/Viego.gif',
 'Vi': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vi_0.jpg',
 'Velkoz': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Velkoz_0.jpg',
 'Veigar': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Veigar_0.jpg',
 'Vayne': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Vayne_0.jpg',
 'Varus': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Varus_0.jpg',
 'Urgot': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Urgot_0.jpg',
 'Udyr': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Udyr_0.jpg',
 'Twitch': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Twitch_0.jpg',
 'Twisted Fate': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/TwistedFate_0.jpg',
 'Tryndamere': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Tryndamere_0.jpg',
 'Trundle': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Trundle_0.jpg',
 'Tristana': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Tristana_0.jpg',
 'Thresh': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Thresh_0.jpg',
 'Teemo': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Teemo_0.jpg',
 'Taric': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taric_0.jpg',
 'Talon': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Talon_0.jpg',
 'Taliyah': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Taliyah_0.jpg',
 'Tahm Kench': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/TahmKench_0.jpg',
 'Syndra': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Syndra_0.jpg',
 'Sylas': 'https://media2.giphy.com/media/XH5DBrjjjWUIBCQ13b/giphy.gif',
 'Swain': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Swain_0.jpg',
 'Soraka': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Soraka_0.jpg',
 'Sona': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sona_0.jpg',
 'Skarner': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Skarner_0.jpg',
 'Sivir': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sivir_0.jpg',
 'Sion': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sion_0.jpg',
 'Singed': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Singed_0.jpg',
 'Shyvana': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shyvana_0.jpg',
 'Shen': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shen_0.jpg',
 'Shaco': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Shaco_0.jpg',
 'Sett': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sett_0.jpg',
 'Seraphine': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Seraphine_0.jpg',
 'Senna': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Senna_0.jpg',
 'Sejuani': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Sejuani_0.jpg',
 'Samira': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Samira_0.jpg',
 'Ryze': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ryze_0.jpg',
 'Rumble': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rumble_0.jpg',
 'Riven': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Riven_0.jpg',
 'Rengar': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rengar_0.jpg',
 'Renekton': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Renekton_0.jpg',
 'Rell': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rell_0.jpg',
 'Rek Sai': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/RekSai_0.jpg',
 'Rammus': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rammus_0.jpg',
 'Rakan': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Rakan_0.jpg',
 'Quinn': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Quinn_0.jpg',
 'Qiyana': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Qiyana_0.jpg',
 'Pyke': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pyke_0.jpg',
 'Poppy': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Poppy_0.jpg',
 'Pantheon': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Pantheon_0.jpg',
 'Ornn': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ornn_0.jpg',
 'Orianna': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Orianna_0.jpg',
 'Olaf': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Olaf_0.jpg',
 'Nunu': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nunu_0.jpg',
 'Nocturne': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nocturne_0.jpg',
 'Nidalee': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nidalee_0.jpg',
 'Neeko': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Neeko_0.jpg',
 'Nautilus': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nautilus_0.jpg',
 'Nasus': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nasus_0.jpg',
 'Nami Aquamancienne': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Nami_0.jpg',
 'Morgana': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Morgana_0.jpg',
 'Mordekaiser': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Mordekaiser_0.jpg',
 'Wukong': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/MonkeyKing_0.jpg',
 'Miss Fortune': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/MissFortune_0.jpg',
 'Master Yi': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/MasterYi_0.jpg',
 'Maokai': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Maokai_0.jpg',
 'Malzahar': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Malzahar_0.jpg',
 'Malphite': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Malphite_0.jpg',
 'Lux': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lux_0.jpg',
 'Lulu': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lulu_0.jpg',
 'Lucian': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lucian_0.jpg',
 'Lissandra': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lissandra_0.jpg',
 'Lillia': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lillia_0.jpg',
 'Leona': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leona_0.jpg',
 'LeeSin': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/LeeSin_0.jpg',
 'Leblanc': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Leblanc_0.jpg',
 'Kog Maw': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/KogMaw_0.jpg',
 'Kled': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kled_0.jpg',
 'Kindred': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kindred_0.jpg',
 'Khazix': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Khazix_0.jpg',
 'Kennen': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kennen_0.jpg',
 'Kayn': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayn_0.jpg',
 'Kayle': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayle_0.jpg',
 'Katarina': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Katarina_0.jpg',
 'Kassadin': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kassadin_0.jpg',
 'Karthus': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karthus_0.jpg',
 'Karma': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Karma_0.jpg',
 'Kalista': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kalista_0.jpg',
 'Kaisa': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kaisa_0.jpg',
 'Jinx': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_0.jpg',
 'Jhin': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jhin_0.jpg',
 'Jayce': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jayce_0.jpg',
 'Jax': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jax_0.jpg',
 'Jarvan IV': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/JarvanIV_0.jpg',
 'Janna': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Janna_0.jpg',
 'Ivern': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ivern_0.jpg',
 'Irelia': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Irelia_0.jpg',
 'Illaoi': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Illaoi_0.jpg',
 'Heimerdinger': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Heimerdinger_0.jpg',
 'Hecarim': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Hecarim_0.jpg',
 'Graves': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Graves_0.jpg',
 'Gragas': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gragas_0.jpg',
 'Gnar': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gnar_0.jpg',
 'Garen': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Garen_0.jpg',
 'Gangplank': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Gangplank_0.jpg',
 'Galio': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Galio_0.jpg',
 'Fizz': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fizz_0.jpg',
 'Fiora': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiora_0.jpg',
 'Fiddlesticks': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Fiddlesticks_0.jpg',
 'Ezreal': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ezreal_0.jpg',
 'Evelynn': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Evelynn_0.jpg',
 'Elise': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Elise_0.jpg',
 'Ekko': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ekko_0.jpg',
 'Dr Mundo': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/DrMundo_0.jpg',
 'Draven': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Draven_0.jpg',
 'Diana Lune de Sang': 'https://i.imgur.com/ROcCM6a.jpg',
 'Diana': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Diana_0.jpg',
 'Darius': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Darius_0.jpg',
 'Corki': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Corki_0.jpg',
 'Cho gath': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Chogath_0.jpg',
 'Cassiopeia': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Cassiopeia_0.jpg',
 'Camille': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Camille_0.jpg',
 'Caitlyn': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_0.jpg',
 'Braum': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Braum_0.jpg',
 'Brand': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Brand_0.jpg',
 'Blitzcrank': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Blitzcrank_0.jpg',
 'Bard': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Bard_0.jpg',
 'Azir': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Azir_0.jpg',
 'Aurelion Sol': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/AurelionSol_0.jpg',
 'Ashe': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ashe_0.jpg',
 'Aphelios': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aphelios_0.jpg',
 'Annie': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Annie_0.jpg',
 'Anivia': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Anivia_0.jpg',
 'Amumu': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Amumu_0.jpg',
 'Alistar': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Alistar_0.jpg',
 'Akali': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Akali_0.jpg',
 'Ahri': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg',
 'Aatrox': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Aatrox_0.jpg',
 'Gotenks Ssj': 'https://64.media.tumblr.com/54aa913ff9cce5d3b4f36a057065aa5d/tumblr_ngi3t2vSVR1r72ht7o1_500.gif',
 'Majin Vegeta': 'https://cdn.discordapp.com/attachments/804401351080542269/805033738697572362/MAJINVEGETA.gif',
 'Zoroark': '',
 'Son Goku Ssj God': 'https://cdn.discordapp.com/attachments/804401351080542269/804732295503282196/giphy_1.gif',
 'Levi Ackerman': 'https://i.imgur.com/ZO0pHrF.gif',
 'Momousagi': '',
 'Tokikake': '',
 'Sakura (Adulte)': 'https://cdn.discordapp.com/attachments/804401351080542269/808354355744342026/SAKUA.gif',
 'Tenten (Adulte)': 'https://cdn.discordapp.com/attachments/805054171661336590/808368901233573968/TENTEN_ADULTE.gif',
 'Naruto (Chakra Mode)': 'https://cdn.discordapp.com/attachments/702633317786452038/803748002266087424/NARUTO_GIF.gif',
 'Sasuke (Mangekyou Sharingan)': 'https://cdn.discordapp.com/attachments/702633317786452038/803746266622328902/giphy.gif',
 'Itadori (Sukuna)': 'https://cdn.discordapp.com/attachments/804401351080542269/808989274534838293/ITAZDORI_SUKUNA.gif',
 'Black Goku': 'https://pa1.narvii.com/7722/3bf18b2b1a74d4decaa4ba8d2da38cd60fd91954r1-480-378_hq.gif',
 'Eren (Adulte)': 'https://i.imgur.com/oCF05d6.png',
 'Ichigo (Bankai Hollow)': 'https://cdn.discordapp.com/attachments/804401351080542269/806971570358190130/ICHIGO_BANKAI_HOLLWO.gif',
 'Naruto Et Sasuke (Jeunes)': 'https://i.imgur.com/LEN9Al3.gif',
 'Itachi (Anbu)': 'https://cdn.discordapp.com/attachments/804401351080542269/804709043390119946/1ef062225d88f60c043dc25fea3ee713.gif',
 'Jinbe': 'https://i.imgur.com/5ktjcxG.png',
 'Itachi (Akatsuki)': 'https://cdn.discordapp.com/attachments/804401351080542269/804708874573709352/ITACHI.gif',
 'Gon': 'https://cutewallpaper.org/21/gon-freecss-angry/Gon-Freecss-Wiki-Anime-Amino.gif',
 'Kurapika': 'https://cdn.discordapp.com/attachments/804401351080542269/808980144071901194/KURAPIKA.gif',
 'Kirua': 'https://cdn.discordapp.com/attachments/804401351080542269/804727841350352929/49ab24125bf09bad9a774628b1b1fd70.gif',
 'Brook': 'https://cdn.discordapp.com/attachments/805054171661336590/814933196163776512/a_supp.gif',
 'Gaara': 'https://i.imgur.com/39HCNme.png',
 'Minato': 'https://cdn.discordapp.com/attachments/804401351080542269/805038366030430228/c0fd11871a7b28d21b8c07339535012e.gif',
 'Doppio': 'https://cdn.discordapp.com/attachments/804401351080542269/805050600445968434/ezgif.com-gif-maker.gif',
 'Shoto (Glace)': 'https://cdn.discordapp.com/attachments/804401351080542269/809412355724935228/shoto.gif',
 'Son Gohan Ssj': 'https://i.pinimg.com/originals/1b/ae/05/1bae05a99e209bbd39088c1aa9607071.gif',
 'Tobi': 'https://64.media.tumblr.com/a6ac04d437e10a8c383c601e9f8421a6/tumblr_n5vm5cCKrX1qk9powo1_500.gif',
 'Armin (Adulte)': 'https://i.imgur.com/9vJPjKS.png',
 'Mikasa (Adulte)': 'https://i.imgur.com/LkP6V3o.png',
 'Sanji': 'https://cdn.discordapp.com/attachments/804401351080542269/808803993802768424/image0.gif',
 'Fumikage': 'https://cdn.discordapp.com/attachments/804401351080542269/809400829504520192/FUMIKAGE.gif',
 'Megumi (Extension Du Territoire)': 'https://cdn.discordapp.com/attachments/805054171661336590/829318322612731934/MEGUMI.gif',
 'Yasuo Spirit Blossom': 'https://cdn.discordapp.com/attachments/804401351080542269/807016869285986334/YASUO_SPIRIT_BLOSSOM_GIF.gif',
 'Itachi Uchiha (Jeune)': 'https://i.imgur.com/uhIUTkr.png',
 'Kimimaro': 'https://i.imgur.com/OEKnkD4.png',
 'Roronoa Zoro (Chasseur de primes)': 'https://i.imgur.com/Si1VpPh.png',
 'Roronoa Zoro': 'https://i.imgur.com/a9A8mCt.png',
 'Son Goku Ssjb': 'https://cdn.discordapp.com/attachments/805054171661336590/817509639133593660/GOKU_SSJ_BLUE.gif',
 'Kayn Soul Hunter': 'http://ddragon.leagueoflegends.com/cdn/img/champion/splash/Kayn_1.jpg',
 'Darkin Kayn': 'https://i.imgur.com/vTFw0uU.jpeg',
 'Kayn Assassin Ténébreux': 'https://i.imgur.com/rfPTHEe.jpeg',
 'Kirua (God Speed)': 'https://cdn.discordapp.com/attachments/804401351080542269/804729711766011954/cd4e05abdde166571eb0643221028b47.gif',
 'Shoto (Feu)': 'https://cdn.discordapp.com/attachments/804401351080542269/809414586074923048/SHOTO_FIRE.gif',
 'Fumikage (Alter)': 'https://pa1.narvii.com/6889/2f1febcbbe23a2799623600dde41492fc7fc9c97r1-540-304_hq.gif',
 'Kakashi': 'https://cdn.discordapp.com/attachments/804401351080542269/808401405283008593/KAKASHI.gif',
 'Satoru Gojo': 'https://media1.giphy.com/media/272WTdBQv7MWmWZlAb/giphy.gif',
 'Aoi Todo': 'https://i.imgur.com/8GA9RA5.jpg',
 'Nami': 'https://i.imgur.com/ab3ptXk.gif',
 'Nami (Post-Ellipse)': 'https://i.imgur.com/VAbsCsh.gif',
 'Gotenks Ssj Trois': 'https://images6.fanpop.com/image/photos/36200000/Dragon-Ball-Z-image-dragon-ball-z-36230703-500-279.gif',
 'Son Gohan Ssj Deux': 'https://cdn.discordapp.com/attachments/804401351080542269/805112675214163988/GOHAN_SSJ2.gif',
 'Orochimaru': 'https://i.imgur.com/LJuoLh0.gif',
 'Monkey D. Garp': 'https://i.imgur.com/ZLd4sdw.gif',
 'Vegeta Ssjb': 'https://cdn.discordapp.com/attachments/804401351080542269/805035594144677928/VEJITABLUE.gif',
 'Eustass Kid': 'https://i.imgur.com/5WxLV4L.gif',
 'Tsunade': 'https://cdn.discordapp.com/attachments/804401351080542269/808357678472232960/Tsunade.gif',
 'Guts': 'https://cdn.discordapp.com/attachments/805054171661336590/809483232974209094/GIF_GUTS.gif',
 'Griffith': 'https://cdn.discordapp.com/attachments/805054171661336590/809476835502194768/griuffith.gif',
 'Jiraya': 'https://cdn.discordapp.com/attachments/804401351080542269/808356331022319616/JIRAYA.gif',
 'Hashirama Senju': 'https://cdn.discordapp.com/attachments/804401351080542269/807011344858611752/HASHIRAMA.gif',
 'Tobirama': 'https://i.imgur.com/C4vEuaV.png',
 'Sarutobi': 'https://static.wikia.nocookie.net/4f472e0f-17c8-46d0-bcfe-b057d926270e',
 'Madara': 'https://i.imgur.com/c0NF2KN.gif',
 'Luffy (Snake Man)': 'https://i.imgur.com/d8JAW16.gif',
 'Luffy (Gear 4)': 'https://i.imgur.com/iwHCO0l.gif',
 'Nanami': 'https://cdn.discordapp.com/attachments/805054171661336590/809472344636391464/NANAMI.gif',
 'God Staff Jax': 'https://i.pinimg.com/originals/41/70/fe/4170fefd47ec15770111aeab3be896f2.jpg',
 'Black Goku Rose': 'https://i.imgur.com/tDbGd8x.gif',
 'Zed Fleau Galactique': 'https://cdn.discordapp.com/attachments/702633317786452038/803703441095917568/tenor.gif',
 'Naruto (Rikudo)': 'https://cdn.discordapp.com/attachments/804401351080542269/808656664982061056/NARUTO_RIKUDO.gif',
 'Sasuke (Rikudo)': 'https://cdn.discordapp.com/attachments/804401351080542269/808690075570798592/original_1.gif',
 'Gaara (Kazekage)': 'https://cdn.discordapp.com/attachments/804401351080542269/804770688149356614/original.gif',
 'Roronoa Zoro Wano': 'https://i.imgur.com/fPok6pt.gif',
 'Dio Brando': 'https://cdn.discordapp.com/attachments/804401351080542269/804783729112776774/29893362e30fc026f281d91d9868cf9b.gif',
 'Eren (Forme Titanesque)': 'https://i.imgur.com/ebY2g4M.gif',
 'Armin (Forme Titanesque)': 'https://cdn.discordapp.com/attachments/804401351080542269/808590215190675466/COLOSSAL_ARMIN.gif',
 'Chopper (Monster Point)': 'https://i.imgur.com/TgS2VPB.png',
 'King': 'https://i.imgur.com/wq5sEZ7.png',
 'Grizzly': 'https://i.imgur.com/tyzdvK6.png',
 'Naruto et Sasuke': 'https://i.imgur.com/9KWSk6u.gif',
 'Yone Spirit Blossom': 'https://i.imgur.com/NCu4Qz3.jpg',
 'Kurapika (Emperor Time)': 'https://cdn.discordapp.com/attachments/804401351080542269/808705434286030859/ezgif.com-gif-maker.gif',
 'Gon (Nen Noir)': 'https://cdn.discordapp.com/attachments/804401351080542269/804712892704227338/ezgif.com-gif-maker_4.gif',
 'Gogeta': 'https://cdn.discordapp.com/attachments/804401351080542269/804778105972457472/Gogeta.gif',
 'Minato (Edo Tensei)': 'https://i.imgur.com/ru09aIy.gif',
 'Kira': 'https://cdn.discordapp.com/attachments/805054171661336590/808413553840226334/KIRA.gif',
 'Diavolo': 'https://i.pinimg.com/originals/7b/5e/4e/7b5e4ec1584b85cb60b20fb6ad72f6e1.gif',
 'Lucario': 'https://i.imgur.com/3q3fgJL.gif',
 'Josuke': 'https://cdn.discordapp.com/attachments/803791953376182272/805108236269125672/image0.gif',
 'Giorno': 'https://thumbs.gfycat.com/TintedBelatedCollardlizard-size_restricted.gif',
 'Jotaro': 'https://i.pinimg.com/originals/e3/48/53/e348530d5f257ea9d3dacca71639f9f8.gif',
 'Hisoka': 'https://cdn.discordapp.com/attachments/803791953376182272/805107616232898570/image0.gif',
 'Kuroro Lucifer': 'https://cdn.discordapp.com/attachments/804401351080542269/807016323476488192/KURORO.gif',
 'Marshall D. Teach (Barbe Noire)': 'https://i.imgur.com/Zqm2RXU.png',
 'Marshall D. Teach': 'https://i.imgur.com/pa0pihq.gif',
 'Marshall D. Teach (Gura Gura No Mi)': 'https://i.imgur.com/OO8RgE7.jpg',
 'Kizaru': 'https://cdn.discordapp.com/attachments/805054171661336590/816968499309969408/kizaru.gif',
 'Akainu': 'https://i.imgur.com/OkB0Vk3.gif',
 'Aokiji': 'https://i.imgur.com/LCqY9UI.gif',
 'Kuzan': 'https://i.imgur.com/JtI2lxY.gif',
 'Smoker': 'https://i.imgur.com/3vJPaRx.gif',
 'Crocodile': 'https://i.imgur.com/H1BwUuK.gif',
 'Monkey D. Dragon': 'https://i.imgur.com/HAwyWWe.gif',
 'Kisuke Urahara': 'https://cdn.discordapp.com/attachments/804401351080542269/806980893653729320/URAHARA.gif',
 'Yoruichi': 'https://cdn.discordapp.com/attachments/804401351080542269/808991042899542036/1518391789_giphy.gif',
 'Soi Fon': 'https://cdn.discordapp.com/attachments/804401351080542269/808990659540287488/3130014990_1_2_BPWPR1Bv.gif',
 'Obito (Rinnegan)': 'https://cdn.discordapp.com/attachments/805054171661336590/807178343975092234/OBITO_RINNEGAN.gif',
 'Shota Aizawa': 'https://i.imgur.com/keNFOMy.gif',
 'Dabi': 'https://i.imgur.com/AoeEpNd.gif',
 'All Might': 'https://64.media.tumblr.com/acaed0de529ab1436f3dee4a348804da/tumblr_pa8u6dNVCZ1r2hy3ro2_540.gifv',
 'Lugia': 'https://i.imgur.com/ctqVQ1R.gif',
 'Fujitora': 'https://i.imgur.com/27FScKO.jpg',
 'Garp et Sengoku': 'https://i.imgur.com/9c8qTqr.gif',
 'Sengoku': '',
 'Ryokugyu': 'https://i.imgur.com/27FScKO.jpg',
 'Mew': 'https://cdn.discordapp.com/attachments/805054171661336590/816970160866983957/MEW.gif',
 'Big Mom': '',
 'Kaido': 'https://i.imgur.com/uenXh7g.png',
 'Big Mom Et Kaido': 'https://i.imgur.com/uenXh7g.png',
 'Edward Newgate (Barbe Blanche) ': 'https://i.imgur.com/BdnDfQj.gif',
 'Kakuzu': 'https://i.imgur.com/BKf04A1.gif',
 'Konan': 'https://i.imgur.com/3mOmZ0v.gif',
 'Trafalgar D. Law': 'https://cdn.discordapp.com/attachments/814587312007675955/814937034090479656/ezgif.com-gif-maker_4.gif',
 'Portgas D. Ace': 'https://i.imgur.com/8AGmDrS.gif',
 'Rayleigh': 'https://i.imgur.com/HzaJdFI.gif',
 'Shanks': 'https://i.imgur.com/IwGDEdb.gif',
 'Ho-Oh': 'https://cdn.discordapp.com/attachments/805054171661336590/814879345297457152/Ho_oh.gif',
 'Mega Dracaufeu': '',
 'Yasuo et Yone': 'https://notagamer.net/wp-content/uploads/2020/12/wallpapersden.com_yasuo-and-yone-league-of-legends_wxl.jpg',
 'King Kong': 'https://cdn.discordapp.com/attachments/804401351080542269/804404708117708840/ezgif.com-gif-maker_1.gif',
 'Jiraya Et Tsunade': 'http://1.bp.blogspot.com/-2TcriCxQd48/UJV2E3gaLaI/AAAAAAAAAPU/7rSuMgHv4ug/s1600/tumblr_mcwpi8GhNE1ru1u75o1_500.gif',
 'Obito (Rikudo)': 'https://cdn.discordapp.com/attachments/805054171661336590/807183278020362250/OBITO_RIKUDO_ETERNAL.gif',
 'Sukuna': 'https://i.imgur.com/V0E7mIF.png',
 'Son Goku SSJ1 (Namek)': 'https://i.imgur.com/TNtvbaS.gif',
 'Son Goku (Namek)': 'https://i.imgur.com/lQLGGHv.gif',
 'Son Goku Ultra Instinct': 'https://i.pinimg.com/originals/f3/85/20/f3852049a78fa952bb7a4774a40017db.gif',
 'Sasuke (Adulte)': 'https://i.imgur.com/1mtaSnt.gif',
 'Madara (Rikudo)': 'https://i.imgur.com/yase4qq.gif',
 'Naruto Et Sasuke (Adultes)': 'https://cdn.discordapp.com/attachments/804401351080542269/804704386869624862/f3232709e7b989b5c6986075d7545105.gif',
 'Godzilla': 'https://cdn.discordapp.com/attachments/804401351080542269/804401425877827605/ezgif.com-gif-maker.gif',
 'Ichigo Mugetsu': 'https://cdn.discordapp.com/attachments/804401351080542269/804628452677386250/MUGETSU.gif',
 'Gon (Adulte)': 'https://cdn.discordapp.com/attachments/804401351080542269/804712193508900872/ezgif.com-gif-maker_3.gif',
 'Gogeta Ssjb': 'https://cdn.discordapp.com/attachments/804401351080542269/804779641188515880/ecf6841c2610803559c41ba7c190db05.gif',
 'Giorno (Requiem)': 'https://cdn.discordapp.com/attachments/804401351080542269/805047540021723177/GIORNO_GIOVANNA.gif',
 'Minato (Edo Tensei Kcm)': 'https://cdn.discordapp.com/attachments/804401351080542269/805042252379455498/SaltyLateBasil-small.gif',
 'Hashirama (Edo Tensei)': 'https://cdn.discordapp.com/attachments/804401351080542269/808633710487273482/HASHIRAMA_EDO_TENSEI.gif',
 'Tobirama (Edo Tensei)': 'https://cdn.discordapp.com/attachments/804401351080542269/808634674468356156/TOBIRAMA_EDO_TENSEI.gif',
 'Sarutobi (Edo Tensei)': 'https://cdn.discordapp.com/attachments/804401351080542269/808636747843502080/SARUTOBI_EDO_TENSEI.gif',
 'Naruto (Hokage)': 'https://i.imgur.com/tmKJNrS.gif',
 'Mewtwo': 'https://i.imgur.com/UOq9Bej.gif',
 'Miruki Zoldick': 'https://i.imgur.com/mlHY0p4.png',
 'Kikyô Zoldick': 'https://i.imgur.com/dR5KneW.png',
 'Zeno et Silva': 'https://i.imgur.com/NYOPr6T.gif',
 'Silva Zoldick': 'https://i.imgur.com/K8TUsWM.png',
 'Zeno Zoldick': 'https://i.imgur.com/inIqhEg.gif',
 'Kon (hxh)': 'https://i.imgur.com/UZ1IyPY.png',
 'Mito Freecss': 'https://i.imgur.com/Yy7iG5d.png',
 'Isaac Netero': 'https://cdn.discordapp.com/attachments/805054171661336590/830403007178080286/KSLHxnA.gif',
 'Hanzo (hunter)': 'https://i.imgur.com/SODUkcJ.png',
 'Irumi Zoldik': 'https://i.imgur.com/tFOQgXs.gif',
 'Beans': 'https://i.imgur.com/ux2UOhx.png',
 'Leolio Paradinaito': 'https://i.imgur.com/NBFxlLS.gif',
 'Kaito': 'https://i.imgur.com/RehnXP7.gif',
 'Knuckle Bain': 'https://i.imgur.com/1xYVr11.png',
 'Ging Freecss': 'https://i.imgur.com/VOtkd0O.gif',
 'Shoot MacMahon': 'https://i.imgur.com/pb02cNk.png',
 'Satotsu': 'https://i.imgur.com/7dDY1FS.png',
 'Pokkuru': 'https://i.imgur.com/7A9UCci.png',
 'Pamu Shiberia': 'https://i.imgur.com/8eLz5Pr.png',
 'Morau McCarnathy': 'https://i.imgur.com/A1qgN2P.gif',
 'Menchi': 'https://i.imgur.com/2KpNs1q.png',
 'Pariston Hill': 'https://i.imgur.com/rt7RgNf.gif',
 'Kanzai': 'https://i.imgur.com/pzXCQYT.png',
 'Piyon': 'https://i.imgur.com/kml4Ydc.png',
 'Tompa': 'https://i.imgur.com/ms2R2ki.png',
 'Aruka Zoldick': 'https://i.imgur.com/DHIbvOx.gif',
 'Goto': 'https://i.imgur.com/xnoUe0a.png',
 'Kanaria': 'https://i.imgur.com/DxwCSE5.gif',
 'Amane': 'https://i.imgur.com/Wy7a9JO.png',
 'Karuto Zoldick': 'https://i.imgur.com/vCDM9hC.png',
 'Zushi': 'https://i.imgur.com/zFDjx8z.png',
 'Shizuku': 'https://i.imgur.com/IbkxhGl.png',
 'Sharnalk': 'https://i.imgur.com/WKSejg0.gif',
 'Sharnalk (Autopilote)': 'https://i.imgur.com/D6p4OXL.gif',
 'Nobunaga Hazama': 'https://i.imgur.com/0btI8qo.png',
 'Franklin': 'https://i.imgur.com/xoln4Ly.gif',
 'Feitan': 'https://i.imgur.com/X3AVK76.gif',
 'Machi': 'https://i.imgur.com/HCAKZfB.gif',
 'Uvoguine': 'https://cdn.discordapp.com/attachments/805054171661336590/830424622779727902/z.gif',
 'Pakunoda': 'https://i.imgur.com/IxWVTzo.gif',
 'Phinks': 'https://i.imgur.com/k5BLUMw.png',
 'Cheetu': 'https://i.imgur.com/ZqFKcDD.png',
 'Poulpe': 'https://i.imgur.com/rUZrSPx.png',
 'Koruto': 'https://i.imgur.com/QwL2k3G.png',
 'Montutyupi': 'https://i.imgur.com/tWZDibP.png',
 'Shauapufu': 'https://i.imgur.com/CfoSEeD.gif',
 'Neferpito': 'https://i.imgur.com/5PkF2QA.gif',
 'Biscuit Kruger': 'https://i.imgur.com/KPGeqzQ.gif',
 'Meruem': 'https://i.imgur.com/c2CR7Hs.gif',
 'Jonathan Joestar': 'https://i.imgur.com/v5RJkXG.gif',
 'Jonathan Joestar (Faible)': 'https://i.imgur.com/cnfjobj.gif',
 'Baron Zeppeli': 'https://i.imgur.com/NbYYjPZ.png',
 'Robert Speedwagon': 'https://cdn.discordapp.com/attachments/805054171661336590/830499276466552842/zz.gif',
 'Erina Pendleton': 'https://i.imgur.com/YMAh8Ev.png',
 'Poco': 'https://i.imgur.com/BxIrort.png',
 'Lisa Lisa': 'https://i.imgur.com/jmrzAgq.gif',
 'Joseph Joestar': 'https://i.imgur.com/fqZ5qM3.gif',
 'Caesar Zeppeli': 'https://cdn.discordapp.com/attachments/805054171661336590/830501419890769920/zz.gif',
 'Rudol von Stroheim': 'https://i.imgur.com/jaB9h1s.png',
 'Smokey Brown': 'https://i.imgur.com/ic9UnRA.png',
 'Suzie Q': 'https://i.imgur.com/ijkV1UA.png',
 'Cars': 'https://i.imgur.com/S8TPSmr.gif',
 'Esidisi': 'https://i.imgur.com/BWmIO0D.gif',
 'Wamuu': 'https://i.imgur.com/Y1V85fw.png',
 'Santana': 'https://i.imgur.com/5ZHSDjp.png',
 'Straits': 'https://i.imgur.com/qOUYJ1g.png',
 'Muhammad Avdol': 'https://cdn.discordapp.com/attachments/805054171661336590/830784966987087882/abdul.gif',
 'Noriaki Kakyoin': 'https://cdn.discordapp.com/attachments/805054171661336590/830786276219158568/kakyoin.gif',
 'Jean Pierre Polnareff': 'https://i.imgur.com/KilVFzp.gif',
 'Iggy': 'https://i.imgur.com/mo9EJOw.gif',
 'Anne': 'https://i.imgur.com/ZAbm8Di.png'}